### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by entropicus96** [immunoengineer/gliph#14]
I have been trying to run GLIPH2 on my system with reference files from human v2.0. As soon as I run it with centos, I immediately receive a segmentation fault (core dumped) error. The error shows up right after it starts reading sample CDR3 information. The test data from http://50.255.35.37:8080/tools works just fine with no issues. Can someone please help me with this?

**Comment by entropicus96** [comment]
It was spaces. One of my colleagues spotted some spaces in my input tcr file. I used cat file1.txt file2.txt > file3.txt to merge two really big tab delimited text files. My suspicion is if that may have introduced some spaces. Or I may have erred somewhere else. The program works, the input was the problem.

**Comment by nathanin** [comment]
Hi @entropicus96 sorry to bug you through here - I know that this is not a forum per se, but with such niche software there's a relatively limited number of places to reach out for some information.

I'm in the middle of running GLIPH2 via the web portal and I'm noticing that not all of the TCRs I input return in the clusters table. Do you see this in your runs, or know for what reason TCRs might be dropped during analysis?

Cheers!

**Comment by entropicus96** [comment]
Perhaps some of your TCRs did not cluster at all? I would assume there are some TCRs in your input that do not share antigen specificity with any of your other TCRs and hence are left out. You can also try installing and running GLIPH2 on your local system if you want to specify any of the parameters that may affect your output.
